name: delivery_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.0
  url_strategy: ^0.2.0
  go_router: ^14.1.0
  uuid: ^4.4.0
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true